name: Build and Publish Bottles

on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula to build (svt-av1-essential or ffmpeg-custom)'
        required: true
        type: choice
        options:
          - svt-av1-essential
          - ffmpeg-custom
      tag:
        description: 'Tag name for the release (e.g., v3.1.2-bottles)'
        required: true
        type: string
      update-formula:
        description: 'Update formula with bottle blocks and commit'
        required: true
        type: boolean
        default: true

jobs:
  build-bottles:
    name: Build bottles
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew on Linux
        if: runner.os == 'Linux'
        run: |
          # Add Homebrew to PATH on Linux (already installed, just not in PATH)
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Build bottle
        run: |
          # Tap this repository locally
          brew tap fraluc06/ffmpeg-svt-av1-essential "$GITHUB_WORKSPACE"

          # Install build dependencies (use bottles when available)
          brew deps --include-build fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }} | xargs -n1 brew install || true

          # Install formula for bottling
          brew install --build-bottle fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}

          # Create bottle
          brew bottle --json --only-json-tab fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: |
            *.bottle.*
            *.json
          retention-days: 1

  update-formula:
    name: Update formula with bottle blocks
    needs: build-bottles
    if: inputs.update-formula
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottles_*
          merge-multiple: true
          path: bottles

      - name: Display downloaded files
        run: ls -lah bottles/

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge bottle JSON into formula
        run: |
          cd bottles
          for json in *.json; do
            echo "Merging $json into formula..."
            brew bottle --merge --write "$json"
          done

      - name: Create branch and commit formula changes
        env:
          BRANCH_NAME: bottles/${{ inputs.formula }}-${{ inputs.tag }}
        run: |
          git checkout -b "$BRANCH_NAME"
          git add Formula/${{ inputs.formula }}.rb
          git commit -m "Add bottles for ${{ inputs.formula }} - ${{ inputs.tag }}

          Bottles built for:
          - macOS 13 (Ventura)
          - macOS 14 (Sonoma)
          - macOS 15 (Sequoia)
          - Ubuntu 22.04

          🤖 Generated with GitHub Actions" || echo "No changes to commit"
          git push -u origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Add bottles for ${{ inputs.formula }} - ${{ inputs.tag }}" \
            --body "## Bottles generated for ${{ inputs.formula }}

          This PR adds pre-compiled bottles for the following platforms:
          - macOS 13 (Ventura)
          - macOS 14 (Sonoma)
          - macOS 15 (Sequoia)
          - Ubuntu 22.04

          ### Changes
          - Updated \`Formula/${{ inputs.formula }}.rb\` with bottle blocks and SHA256 hashes
          - Bottles are published in release [${{ inputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag }})

          ### Testing
          After merging, users can install with:
          \`\`\`bash
          brew install ${{ inputs.formula }}
          \`\`\`

          🤖 Auto-generated by GitHub Actions" \
            --base main \
            --head bottles/${{ inputs.formula }}-${{ inputs.tag }}

  publish-bottles:
    name: Publish bottles to release
    needs: [build-bottles, update-formula]
    if: always() && needs.build-bottles.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottles_*
          merge-multiple: true
          path: bottles

      - name: Remove JSON files (only publish bottles)
        run: rm -f bottles/*.json

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tag }}
        run: |
          gh release create "$TAG_NAME" \
            --repo ${{ github.repository }} \
            --title "Bottles for ${{ inputs.formula }} - $TAG_NAME" \
            --notes "Pre-compiled bottles for ${{ inputs.formula }}

          **Supported platforms:**
          - macOS 13 (Ventura)
          - macOS 14 (Sonoma)
          - macOS 15 (Sequoia)
          - Ubuntu 22.04

          **Installation:**
          Download the appropriate bottle for your platform and install with:
          \`\`\`bash
          brew install ${{ inputs.formula }}
          \`\`\`

          Or download bottles from this release and use:
          \`\`\`bash
          brew install --bottle <path-to-bottle>
          \`\`\`

          🤖 Built with GitHub Actions" \
            bottles/*

      - name: List uploaded files
        run: ls -lah bottles/
