name: Build and Publish Bottles

on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula to build (svt-av1-essential or ffmpeg-custom)'
        required: true
        type: choice
        options:
          - svt-av1-essential
          - ffmpeg-custom
      tag:
        description: 'Tag name for the release (e.g., v3.1.2-bottles)'
        required: true
        type: string
      update-formula:
        description: 'Update formula with bottle blocks and commit'
        required: true
        type: boolean
        default: true

jobs:
  build-bottles:
    name: Build bottles
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew on Linux
        if: runner.os == 'Linux'
        run: |
          # Add Homebrew to PATH on Linux (already installed, just not in PATH)
          echo "/home/linuxbrew/.linuxbrew/bin" >> "$GITHUB_PATH"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Build bottle
        run: |
          # Tap this repository locally
          brew tap fraluc06/ffmpeg-svt-av1-essential "$GITHUB_WORKSPACE"

          # Install build dependencies (use bottles when available)
          brew deps --include-build fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }} | xargs -n1 brew install || true

          # Install formula for bottling
          brew install --build-bottle fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}

          # Create bottle
          brew bottle --json --only-json-tab fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: |
            *.bottle.*
            *.json
          retention-days: 1

  update-formula:
    name: Update formula with bottle blocks
    needs: build-bottles
    if: inputs.update-formula
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottles_*
          merge-multiple: true
          path: bottles

      - name: Validate downloaded bottles
        run: |
          echo "Validating downloaded bottles..."
          json_count=$(find bottles -name "*.json" -type f | wc -l)
          bottle_count=$(find bottles -name "*.bottle.*" ! -name "*.json" -type f | wc -l)

          echo "Found $json_count JSON files and $bottle_count bottle files"

          if [ "$json_count" -eq 0 ]; then
            echo "Error: No JSON files found!"
            exit 1
          fi

          if [ "$bottle_count" -eq 0 ]; then
            echo "Error: No bottle files found!"
            exit 1
          fi

          echo "Contents:"
          ls -lah bottles/

      - name: Create and checkout new branch
        env:
          BRANCH_NAME: bottles/${{ inputs.formula }}-${{ inputs.tag }}
        run: |
          git checkout -b "$BRANCH_NAME"

      - name: Tap repository locally
        run: |
          # Remove existing tap if present
          brew untap fraluc06/ffmpeg-svt-av1-essential 2>/dev/null || true

          # Tap local workspace
          brew tap fraluc06/ffmpeg-svt-av1-essential "$GITHUB_WORKSPACE"

      - name: Configure Git
        run: |
          # Configure globally for Homebrew operations
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge bottle JSON into formula
        env:
          ROOT_URL: https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag }}
        run: |
          cd bottles

          # Check if there are any JSON files
          if ! compgen -G "*.json" > /dev/null; then
            echo "Error: No JSON files to merge"
            exit 1
          fi

          for json in *.json; do
            echo "Merging $json into formula with root_url: $ROOT_URL"
            if ! brew bottle --merge --write --root-url="$ROOT_URL" "$json"; then
              echo "Error: Failed to merge $json"
              exit 1
            fi
          done

          cd ..

          # Verify formula contains bottle block
          echo "Verifying formula was updated..."
          if grep -q "bottle do" Formula/${{ inputs.formula }}.rb; then
            echo "✓ Bottle block found in formula"
            echo "Bottle block content:"
            sed -n '/bottle do/,/^  end$/p' Formula/${{ inputs.formula }}.rb
          else
            echo "Error: No bottle block found in formula after merge"
            exit 1
          fi

      - name: Push changes
        env:
          BRANCH_NAME: bottles/${{ inputs.formula }}-${{ inputs.tag }}
        run: |
          # Push branch with commits made by brew bottle --merge
          git push -u origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          existing_pr=$(gh pr list --head bottles/${{ inputs.formula }}-${{ inputs.tag }} --json number --jq '.[0].number' || echo "")

          if [ -n "$existing_pr" ]; then
            echo "PR #$existing_pr already exists, skipping creation"
            exit 0
          fi

          gh pr create \
            --title "Add bottles for ${{ inputs.formula }} - ${{ inputs.tag }}" \
            --body "## Bottles generated for ${{ inputs.formula }}

          This PR adds pre-compiled bottles for the following platforms:
          - macOS 13 (Ventura)
          - macOS 14 (Sonoma)
          - macOS 15 (Sequoia)
          - Ubuntu 22.04

          ### Changes
          - Updated \`Formula/${{ inputs.formula }}.rb\` with bottle blocks and SHA256 hashes
          - Bottles are published in release [${{ inputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag }})

          ### Testing
          After merging, users can install with:
          \`\`\`bash
          brew install fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}
          \`\`\`

          🤖 Auto-generated by GitHub Actions" \
            --base main \
            --head bottles/${{ inputs.formula }}-${{ inputs.tag }}

  publish-bottles:
    name: Publish bottles to release
    needs: [build-bottles, update-formula]
    if: |
      needs.build-bottles.result == 'success' &&
      (needs.update-formula.result == 'success' || needs.update-formula.result == 'skipped')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all bottle artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottles_*
          merge-multiple: true
          path: bottles

      - name: Validate and prepare bottles for release
        run: |
          echo "Validating bottles for release..."

          # Remove JSON files (only publish bottles)
          rm -f bottles/*.json

          # Count remaining bottle files
          bottle_count=$(find bottles -name "*.bottle.*" -type f | wc -l)

          if [ "$bottle_count" -eq 0 ]; then
            echo "Error: No bottle files to publish!"
            exit 1
          fi

          echo "Found $bottle_count bottle files to publish:"
          ls -lah bottles/

      - name: Create or update Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tag }}
        run: |
          # Check if release already exists
          if gh release view "$TAG_NAME" --repo ${{ github.repository }} >/dev/null 2>&1; then
            echo "Release $TAG_NAME already exists, uploading bottles to existing release..."

            # Upload bottles to existing release
            for bottle in bottles/*; do
              echo "Uploading $(basename "$bottle")..."
              gh release upload "$TAG_NAME" "$bottle" \
                --repo ${{ github.repository }} \
                --clobber
            done
          else
            echo "Creating new release $TAG_NAME..."

            # Create new release with bottles
            gh release create "$TAG_NAME" \
              --repo ${{ github.repository }} \
              --title "Bottles for ${{ inputs.formula }} - $TAG_NAME" \
              --notes "Pre-compiled bottles for ${{ inputs.formula }}

          **Supported platforms:**
          - macOS 13 (Ventura)
          - macOS 14 (Sonoma)
          - macOS 15 (Sequoia)
          - Ubuntu 22.04

          **Installation:**
          After the corresponding PR is merged, install with:
          \`\`\`bash
          brew install fraluc06/ffmpeg-svt-av1-essential/${{ inputs.formula }}
          \`\`\`

          Or download bottles manually from this release and install with:
          \`\`\`bash
          brew install --bottle <path-to-bottle>
          \`\`\`

          🤖 Built with GitHub Actions" \
              bottles/*
          fi

      - name: Verify release and list assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tag }}
        run: |
          echo "Release $TAG_NAME created/updated successfully!"
          echo "Assets in release:"
          gh release view "$TAG_NAME" --repo ${{ github.repository }} --json assets --jq '.assets[].name'
